### ISSUE TITLE
Transactions Previous and Next on top

### ISSUE THREAD

**Issue by BroadcastJunkie** [ArkEcosystem/explorer#260]
Please add a previous and next button to the top of the transaction page.  Right now, you have to scroll to the bottom of each transaction page to find next and back.  A set up top would be nice, and make navigation of the transaction log faster.

**Comment by dated** [comment]
Personally i'm against such a change. When skimming through the transactions the flow is from top to button. We will have (better) filtering with Core 2.0 anyway, which should make such a change obsolete.

**Comment by BroadcastJunkie** [comment]
If it changes in v2 its fine. Right now, its a bit annoying. Not sure how scrolling to the bottom each time is good.. but maybe add a transactions per page or at least a page number selector. Right now the best option is to go into the address bar and change the page. Which for something like ark who wants to be simple, should be. So whether you or I are against, its about ease of use. If I gave you a million page forum, and said you have to scroll page by page, and had to go to the bottom each time to go to the next page, and you had to go to page 5000 you'd probably say no.  and to be honest, I don't think its a major change, its just navigational. just my two cents.
Thanks for the reply!

**Comment by faustbrian** [comment]
Will close this for, might revisit it later on.
