### ISSUE TITLE
UX: content header on transaction pages

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/explorer#264]
The content header on the wallet/transactions block/transactions (#263) pages gives no context about what transactions are being shown. This can only be deduced by looking at the url.

Adding the wallet-details and block-identity respectively would provide that context.

**Comment by dated** [comment]
I was thinking about a stripped down version of the wallet-details component, something like this:

![image](https://user-images.githubusercontent.com/6547002/41196317-4cb0f0b0-6c3d-11e8-9584-9c846f98cb09.png)

Another option would be to put the address next to the content tile, as is currently done with the delegates name on the voters page right now:

![image](https://user-images.githubusercontent.com/6547002/41196330-8f0e65aa-6c3d-11e8-9041-aa39081602c2.png)

Maybe the designer can chop in on this, @faustbrian.

**Comment by dated** [comment]
👍

**Comment by faustbrian** [comment]
@dated how is it coming along

**Comment by dated** [comment]
on it now, busy week :/
