### ISSUE TITLE
Explorer shows wrong delegate data on the devnet

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/explorer#285]
We just came across this on #devnet on Slack. Screenshots:

![](https://i.gyazo.com/689ebde44a9d0e1fabd0723f82a3349d.png)
https://dexplorer.ark.io/wallets/D6Ai2i6EEdAr4QGkVTicrecVfhN9yF9sPk

![Infine forged dArk](https://i.gyazo.com/37e75d1e54678a23377c7735931045d2.png)
Infine forged dArk

![Forged amount is a chipmunk emoji, lol](https://i.gyazo.com/4a986c074de122c720eb2e164e8635b6.png)
Forged amount shows a chipmunk emoji

It seems to be isolated to the v3 Explorer, as the API returns correct amounts, and so does the v1 Explorer.

**Comment by ItsANameToo** [comment]
I think it is an issue with the dexplorer api, as it returns forge amounts that are incorrect. For example: [boldninja](https://dexplorer.ark.io:8443/api/delegates/forging/getForgedByAccount?generatorPublicKey=03089a66fac174ad94dfa07ec50b41545cd1d5696af0c9f34ed306ff8d7f1d4ba6) has forged `8700000002365000000000` on devnet, while a [delegate on mainnet](https://explorer.ark.io:8443/api/delegates/forging/getForgedByAccount?generatorPublicKey=02b1d2ea7c265db66087789f571fceb8cc2b2d89e296ad966efb8ed51855f2ae0b) forged `18983960000000` (so a difference of 8 `0`'s), so probably the api doesn't divide by Math.pow(10,8) somewhere :P

**Comment by dated** [comment]
From the boldninja example it seems as if the fees and rewards get concatenated, not added.

**Comment by ItsANameToo** [comment]
@dated correct, already opened a PR for that ArkEcosystem/core#655

**Comment by ItsANameToo** [comment]
PR has been merged, should now be fixed :)
