### ISSUE TITLE
A new delegate doesn't show up in active delegates list until it forges for the first time.

### ISSUE THREAD

**Issue by geops22** [ArkEcosystem/explorer#308]
A new delegate that joins the active list doesn't show up until it forges its first block. If it is offline and only misses blocks it never shows up in the list. The delegate monitor page just skips the row where it should be and that position number is not in the list, e.g. if it's number 38 then number 38 is not listed at all. It is however counted as a "Not Forging".
The easiest way to reproduce this is to register a new delegate and vote it in the active list but don't actually spin up the node. The "Not Forging" number will increment but the delegate will never show up in the list.

**Comment by dated** [comment]
I believe this is caused by an error in the tooltip, causing the row not to be displayed. I'll confirm and have a PR ready in a bit.
