### ISSUE TITLE
Make e2e test fail less often

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#310]
**Describe the bug**
Some e2e tests fail due to parts of the website not loading in time / Travis being too quick, making the tests fail (for example: expecting a link to be there and pressing it before it has actually been loaded). It can be difficult to reproduce some of these issues locally, as they don't seem to fail when I run them on my machine (10+ tries without issue), while is happens often with Travis.

**To Reproduce**
Just look through the commits, sometimes the test suite fails

**Expected behavior**
Don't fail if there's no issue

**Screenshots**
n/a

**Server (please complete the following information):**
n/a

**Additional context**
We should look into the failing tests and see what can be done to make them more robust; then apply that also to some of the other e2e that pose the same risks

**Comment by faustbrian** [comment]
@ItsANameToo can you take another look at this sometime these days?

**Comment by ItsANameToo** [comment]
Yes

**Comment by ItsANameToo** [comment]
Additional information: changed the failing test (and some other tests that are candidates for the same issue) to make use of a more specific `waitForElementVisible`. The issue was with the url assert being done before the new page was loaded correctly (since we were waiting for an element that was visible on both pages). This is now fixed as we wait for a more indicative element that does only appears on one of the pages. 

What still has to be done before we can close the issue:

- [ ] Look into the current issue where seemingly-equal values are not equal (example: [Failed [notEqual]: ('5190233725662471137' != '5190233725662471137')  - expected "5190233725662471137" but got: "5190233725662471137"](https://travis-ci.org/ArkEcosystem/explorer/jobs/410207102))
- [ ] Go over the tests that wait for elements that could be present earlier than the element / part of the browser that is required for the next step. Although this should not happen often in the tests (as we normally wait for the element that we want to use), it can occur with some of the url assertion tests and possibly others.

**Comment by dated** [comment]
The problem with those tests is also that the values of the elements get parsed to early imho, before they are actually replaced. I tried using `waitForElementNotVisible` to detect the change in the elements content but had no luck so far.

**Comment by dated** [comment]
`waitForElementNotPresent` however seems to do the job.

![image](https://user-images.githubusercontent.com/6547002/43488943-9b3c836e-951b-11e8-8afe-35b5030d5996.png)

i'll update my tests and remove the `notEqual` assertion.

**Comment by ItsANameToo** [comment]
Nice one @dated

**Comment by dated** [comment]
It failed again unfortunately. I'm pretty positive that it's just a latency issue at this point. Increasing the timeout from 10 to 20 seconds (or 30 to be extra safe) could fix this once and for all.

**Comment by faustbrian** [comment]
Tests seem to run pretty stable now.
