### ISSUE TITLE
ARK explorer website (explorer.ark.io) is using tcp/8443 behind the scenes

### ISSUE THREAD

**Issue by rdk1979** [ArkEcosystem/explorer#324]
**Describe the bug**
If you're behind a corporate firewall that for example only allows HTTP(S) traffic you can't reach the ARK explorer at https://explorer.ark.io.

A netstat -n shows me that my laptop is trying to open TCP/8443 to IP 104.25.220.25.

**To Reproduce**
1. make sure port TCP/8443 is closed on your firewall.
2. Goto https://explorer.ark.io
3. you'll see that "latest transactions" and "latest blocks" keep loading forever. (3 flashing dots)

**Expected behavior**
A website over an secure SSL (tcp/443) connection should preferably not use any other port in the background.

This issue occurs on every system with IE, Edge, Chrome, Firefox, etc.

**Comment by Neurone** [comment]
This is not a real issue of the explorer, it's more a configuration _bother_. API are served by ARK node, not by the explorer, so any node can serve the explorer well. I think the best approach is to allow changing the ARK node to use while surfing the explorer: it should be nice to have an option to change that configuration in the top bar, the same way I change the ARK/currency value, or enable/disable dark mode.
