### ISSUE TITLE
Use local time zone and display time zone used

### ISSUE THREAD

**Issue by blmatthews** [ArkEcosystem/explorer#349]
Timestamps are displayed in UTC+7. The only way I know that is going to the list of latest transactions (or using a transaction that I know when it took place via some external mechanism) and calculating the offset from my current time, which doesn't seem like something everyone should have to do. So I have two requests:

- Display the time zone used, either next to any timestamp, or at the bottom of the page, or something like that.
- Determine the browser's time zone and use that (and still do the previous).

As a bonus, also display dates using either a localized format or yyyy.mm.dd. Currently it's dd.mm.yyyy, which is ambiguous if the day is <=12, and doesn't sort as easily as yyyy.mm.dd.

**Comment by dated** [comment]
Are you still experiencing this? The date formatting has been tackled in #360 and is now based on your browsers locale.

**Comment by blmatthews** [comment]
I now see the date format as mm.dd.yyyy, but it's still in UTC+7 (I'm UTC-7), and nowhere I can see does it say what time zone it's using, I had to figure it out (so I may be wrong :-) ), so yes, still experiencing this.

**Comment by dated** [comment]
I've identified the issue I think, will do some testing.

**Comment by ItsANameToo** [comment]
@faustbrian plz close
