### ISSUE TITLE
Pricing of transactions

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/explorer#361]
Adding pricing of transactions to the explorer like etherscan. So you can see value at the time that the transaction was send.

**Comment by boldninja** [comment]
@dated want to take a stab?

**Comment by dated** [comment]
On it. I would just add the FIAT value as a tooltip though, shown in the currently selected currency. I wouldn't add extra columns or rows to the various tables. What do you say @boldninja?

e.g.
![image](https://user-images.githubusercontent.com/6547002/44667672-be661480-aa1b-11e8-8766-ce87369023ab.png)

**Comment by dated** [comment]
Oh wait. We want the historic value.

**Comment by faustbrian** [comment]
I would simply use CryptoCompare and cache the closing prices of a day on the fly. By on the fly I mean that instead of pulling and caching all prices I would fetch a price for a specific day when a transaction is opened.

Lets say I open a transaction from the 27.04.2017, then you would fetch the closing price of that day and store it in the localStorage and vuex.

**Comment by boldninja** [comment]
daily closing average ?

**Comment by dated** [comment]
CryptoCompare allows us to retrieve the rate for a given timestamp. This wouldn't bloat localStorage but would mean one API request per viewed transaction.

**Comment by faustbrian** [comment]
You could still store it in localStorage per timestamp.

**Comment by dated** [comment]
That'd increase the bloat even more imho as transactions with the same timestamp are rather uncommon (except for some pools which process their payouts without artificial delay).

**Comment by faustbrian** [comment]
Yeah, I would just cache it based on day.

**Comment by dated** [comment]
Well, this took me longer than planned. I'll add some tests and try to push this tonight.

I store the historical average rates in localStorage, the last retrieved conversion rate in vuex. If the conversion rate is not found in either of those I make an API call.

**Comment by dated** [comment]
This can be closed i believe?

**Comment by ItsANameToo** [comment]
@faustbrian plz close
