### ISSUE TITLE
Add "24hr Stats" to Explorer

### ISSUE THREAD

**Issue by doubled1c3** [ArkEcosystem/explorer#372]
**Is your feature request related to a problem? Please describe.**
There isn't an intuitive way to detect overall network activity over the last 24 hours

**Describe the solution you'd like**
A bar of text on the homepage, maybe under the graph, showing some variables

*24hr ARK Transaction Volume:* How much ARK was exchanged across various ARK addresses over the last 24 hours, in total.
*24hr Fiat Transaction Volume:* How much Fiat value did the network facilitate in the last 24 hours
*24hr Active Wallets:* How many wallets "did something" in the last 24hrs (vote, unvote, send, receive, register delegate, but not double count wallets. If they did anything, they count, if they did nothing, they don't)
*24hr Address Growth:* How many ARK addresses came into existence with an initial transaction over the last 24hrs.

Anything else you find relevant for a 24hr period

**Describe alternatives you've considered**
This is something put forward from alexesm after it was seen on a different coin's explorer. I added some additional vars.

**Additional context**
Not critical, but would be cool to have.

**Comment by kristjank** [comment]
Nice, and yeah, a separate page or tab would be great. I would also include the dynamic fee information there (graph,showing min, max ,avg and timeframe related)...

other information will also be there, as a plugin is being developed to handle more data ...(block times, network congestions, etc..) @dated @doubled1c3

**Comment by doubled1c3** [comment]
+1

**Comment by ItsANameToo** [comment]
Currently the count queries (which we would need for the tx amounts per day) are very heavy on the nodes. It's better to wait until core 3.0 to work on an extensive statistics page when we can utilize elastic search.

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
