### ISSUE TITLE
Vote Report Percentage More Specific

### ISSUE THREAD

**Issue by doubled1c3** [ArkEcosystem/explorer#444]
https://explorer.ark.io/VoteReport.txt

Yo I see a minor issue with this resource,

=> Total Votes  : 56.22% ( 77,278,871 / 137,448,952 )

should be more specific, and include a separate percentage that factors out wallets that will not be voting based on principle. Namely, founder's fund and ArkShield

Can call it something like Available Vote Percentage or something, even itemize arkshield balance and founders fund balance and create line items showing results and percentages?

I ask because the percentage always looks worse than it really is, so it should be represented correctly.

This is also arguably the most viewed and refreshed resource in the entire Arkosphere, so may need more attention to best represent what's actually up.

Is this something that can be addressed?

**Comment by boldninja** [comment]
Not sure if this should be part of official info since technically you can still vote even if not voting. There is community link with more info: http://vote.world-domination.org that has that info included. I'm gonna leave this open for discussion and other opinions.

**Comment by dated** [comment]
The vote-report has become a core package by now, where some number sanitation is done already, i.e. filtering out the wallets that have less than 0.1 ARK in holdings. Adding an additional line which represents the reality better sounds like a good idea to me.

The issue/discussion should be moved to https://github.com/arkecosystem/core though.

**Comment by dated** [comment]
Closing this as this is not a feature of the explorer.
