### ISSUE TITLE
Number of transactions not showing in the latest forged block section in Delegate Monitor

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/explorer#489]
**Describe the bug**
The actual number of transactions is missing in the Delegate Monitor in the latest forged block section. Instead it shows "X Ѧ from transactions".

**Expected behaviour**
The number of transactions should be displayed in that section, e.g. "2 Ѧ from 0 transactions".

**Comment by ItsANameToo** [comment]
Running the latest version locally (dev version) shows the "2 Ѧ from 0 transactions", so seems that something is either wrong with the production build, or the official explorers are acting up 🤔

**Comment by ItsANameToo** [comment]
Running production build locally also shows the amount of transactions correctly, so not sure what's up. @faustbrian could it be that the currently deployed explorer is off for some reason?
