### ISSUE TITLE
Fees chart

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/explorer#490]
**Is your feature request related to a problem? Please describe.**
How about a fees chart on the homepage like the price chart? It could have buttons or dropdown for every transaction type.

**Comment by dated** [comment]
There will be a statistics page soon, see #372 ;)

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
