### ISSUE TITLE
Delegate monitor shows vote approval

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/explorer#507]
**Feature Request**
I think vote approval should be changed. This may give impression from ark based on how good they are, instead of how many votes they have. 
Ex.   Should I vote for the delegate with the best returns, whats best for ark, or the delegate with the most approval.
The red arrow shows what I am talking about.

**Describe the solution you'd like**
Vote
Total Votes
Voting Wallets Total
![vote approval](https://user-images.githubusercontent.com/24502401/50320870-4aed8480-049c-11e9-8d93-31bfdb0fb9ee.jpg)

**Comment by skeuo** [comment]
This would probably be best solved by directly replacing the text "approval" with "Voter Percentage" or "Vote %" for a more intuitive association with the percentage value.

**Comment by dated** [comment]
This needs to be changed accross all user facing applications, marking `on hold` for the time being.
