### ISSUE TITLE
Flag to show a wallet name is "known" and not a delegate name

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/explorer#528]
**Is your feature request related to a problem? Please describe.**
With the recent increase of delegate names, I think it may be a good idea to highlight wallet names if they are known in the config (e.g. exchanges, hot wallet, etc)

**Describe the solution you'd like**
Just a small tick or similar icon, possibly with a tooltip, to show we're confident the address is known and legit.

**Comment by dated** [comment]
Like this?

![image](https://user-images.githubusercontent.com/6547002/50514528-0adf6080-0a9f-11e9-93c7-3b9ab97548e9.png)

**Comment by alexbarnsley** [comment]
Looks good to me 👌

**Comment by alexbarnsley** [comment]
Just add a tooltip as well to show it's a known wallet, so newbies understand what that means

**Comment by dated** [comment]
Yea, will finish this in a bit. Gotta run some errands now.
