### ISSUE TITLE
Transaction Filtering on Landing Page

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/explorer#541]
The current design of the transaction filtering stands out too much imho and does not integrate well into the design of the homepage. Also it doesn't respond immediately when the type is changed.

A more minimal design like below would be a better fit imho.

![image](https://user-images.githubusercontent.com/6547002/50847883-fe96b580-1372-11e9-8b99-51ea884426ef.png)

**Comment by olejegcord** [comment]
good idea
Need like this 
![image](https://user-images.githubusercontent.com/36424378/50921733-67545f80-1451-11e9-9a33-c3e34f9d331a.png)

**Comment by dated** [comment]
:+1: i'll change it accordingly!

**Comment by dated** [comment]
There's a small issue with the dropdrown on mobile still, will fix that asap.

**Comment by olejegcord** [comment]
![image](https://user-images.githubusercontent.com/36424378/50967524-08d6c200-14e1-11e9-9865-5fe689ebe1b5.png)

**Comment by dated** [comment]
Will be done!
