### ISSUE TITLE
URL improvements

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/explorer#543]
**Is your feature request related to a problem? Please describe.**
Is it possible to first search the URL param and then show 404 page if no results, so links like these will work?
https://explorer.ark.io/e94bec33c6f02f0ffee76059e0523b830b8da94b289a6499fb8e80f63e2a9df9
https://explorer.ark.io/zillion
https://explorer.ark.io/AJwDCsGDdA8LgiNoxe8XSiwB8rvp8GRZBW
https://explorer.ark.io/025687c1facbaf87b43a46cb78ddec6e4ddb115d1e5a91b53cef5a2c7305a47adc

**Describe the solution you'd like**
I want to be able to paste tx id or wallet id directly after the domain and it will redirect me to the correct page.

Example:
https://explorer.ark.io/e94bec33c6f02f0ffee76059e0523b830b8da94b289a6499fb8e80f63e2a9df9
to redirect me to
https://explorer.ark.io/transaction/e94bec33c6f02f0ffee76059e0523b830b8da94b289a6499fb8e80f63e2a9df9

https://explorer.ark.io/AJwDCsGDdA8LgiNoxe8XSiwB8rvp8GRZBW
to redirect me to
https://explorer.ark.io/wallets/AJwDCsGDdA8LgiNoxe8XSiwB8rvp8GRZBW

**Comment by faustbrian** [comment]
That adds an unnecessary amount of request overhead for something that will be used by almost no one.

**Comment by zillionn** [comment]
I respect your opinion, but if you're not using something that doesn't mean nobody is using it. I'm pasting txid on `btc.com` every day. Think about it.

However, it's not that important.
