### ISSUE TITLE
Can't type into search bar when on mobile

### ISSUE THREAD

**Issue by dvdptr** [ArkEcosystem/explorer#545]
**Describe the bug**
When on mobile (iPhone), search bar of explorer doesn't work as I can't type into it. After pressing the search bar-icon it opens but immediately closes again when trying to type. Issue happens on several browsers like safari, brave, chrome and firefox.

**Expected behavior**
When pressing search bar-icon, text-field should open.

**Comment by dated** [comment]
Can confirm, will take a look at the exact cause momentarily.
