### ISSUE TITLE
0 confirmations tx

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/explorer#548]
Can we make the `0 confirmations` more distinguishable and probably add some text with different color:
`Confirmations: 0 (unconfirmed transaction)`
So it's clear to the user that the tx is not yet confirmed and it may never be.

**Comment by dated** [comment]
Uncofirmed transactions are not considered yet by the explorer - no where does it query the `unconfirmed` endpoints of the API, as mentioned before this is a bug somewhere. I didn't have the time to look at it in detail, but it's either a bug with the confirmation count in the explorer, or the bug originates from the core-api, possibly cache related.
