### ISSUE TITLE
fix: UI improving position of »votes: delegate« bar 

### ISSUE THREAD

**Issue by dvdptr** [ArkEcosystem/explorer#550]
**Is your feature request related to a problem? Please describe.**
This issue is about the position of »votes: delegate-name« bar in the explorer. As it is displayed in it's own bar, it takes a lot of space with 130px in height but there is almost nothing in it. This is related to both: desktop and mobile-view.

**Describe the solution you'd like**
Instead of having the delegate displayed in it's own bar, I'd like to propose to implement it into the information area next to balance and tx in-out. That way the information becomes a part of other listed information.

**Additional context**
Implementing the »vote: delegate-name« into the information block leads to a much easier view of the content, leading to improved UX as unnecessary white-space will be removed. There are several ways to do so. 1) Replacing the tx-field with Delegate information, adding the in- and out graphic next to the address-tab. 2) Replacing the tx-field and find another position for the graphic, for example next to the address. 3) as an alternative the Delegate information could be listed next to address. 

I prepared some very quick sketches so that you get the idea. 

Before (current UI) with bad white-spaced delegate block:

![expl_badui](https://user-images.githubusercontent.com/41017948/51233551-6bf5a800-196a-11e9-82f7-8f870b09aa46.png)

1) Replacing the tx-field with Delegate information, adding the in- and out graphic next to the address-tab:

![expl_impri](https://user-images.githubusercontent.com/41017948/51233586-7e6fe180-196a-11e9-84a4-7a975f8d3a0d.png)

2) Replacing the tx-field and find another position for the graphic, for example next to the address:

![expl_imprii](https://user-images.githubusercontent.com/41017948/51233602-8d569400-196a-11e9-9413-07d7bae5887d.png)

3) as an alternative, the Delegate information could be listed next to address: 

![expl_impriii](https://user-images.githubusercontent.com/41017948/51233627-a101fa80-196a-11e9-9d4a-e2a963e3befd.png)

**Comment by dated** [comment]
This can be closed @faustbrian
