### ISSUE TITLE
bug: smartbridge text overflow

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#617]
**Describe the bug**
With the new 255 smartbridge field, it can overflow if there are no spaces in the text: https://dexplorer.ark.io/transaction/4a9f883adae40c0af85635df7ac306ce530bc6a54f564fb2bc00c3fb2d6421ba . Can probably be fixed by adding `word-break: break-word` to the fields where a smartbridge text can be shown.

**To Reproduce**
See here: https://dexplorer.ark.io/transaction/4a9f883adae40c0af85635df7ac306ce530bc6a54f564fb2bc00c3fb2d6421ba

**Expected behavior**
It should break the text so it doesn't overflow

**Screenshots**
-

**Server (please complete the following information):**
-

**Additional context**
-

**Comment by zillionn** [comment]
https://github.com/ArkEcosystem/desktop-wallet/issues/1222
