### ISSUE TITLE
feat: extend search functionality

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#665]
It would be nice to have a more extensive search functionality in the explorer, e.g:

An autofill option for:
- searching delegates instead of needing a full name match
- searching through `known wallets`

Apart from the above, a search option on vendorfields would also be a great addition. This might need a dedicated search page so different values can be set (e.g. searching for a specific address, between time periods, etc.)

**Comment by dated** [comment]
>searching through known wallets

This is already possible :thinking: 

Regarding the rest: i started to implement that in #655.

**Comment by ItsANameToo** [comment]
I should be clearer: I meant searching for `itsana` and that the search field would have a  dropdown / autofill for  `itsanametoo`

**Comment by ItsANameToo** [comment]
and similar for known wallets so `bitt` for  `bittrex`

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
