### ISSUE TITLE
feat: update pagination options

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#666]
Currently you can only go to `next` or `previous` pages in the wallet. It would be better if there were more paginations options, such  as  `first`, `last` and possibly have shortcuts to go to page 5, 10, etc..

**Comment by dated** [comment]
Might be a good occasion to also include the pagination directly in the table wrapper.

**Comment by dated** [comment]
How's this for starters @ItsANameToo?

![image](https://user-images.githubusercontent.com/6547002/62123963-612cb000-b2c9-11e9-8b73-d9e53781e3b5.png)

**Comment by ItsANameToo** [comment]
massive 😂 I  was personally thinking more in the size of this:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/35610748/62128700-3c3e3a00-b2d5-11e9-8f2c-16a5aac37b91.png">

but I'll run it past Oleg and get back to you

**Comment by dated** [comment]
damn, i'm basically done 😂

**Comment by ItsANameToo** [comment]
Well I don't think you'll have to make functional changes (e.g. my example didn't have the 5 pages in the middle, but I still want that), just that you might have to reduce the padding a bit

**Comment by dated** [comment]
I just made the number of buttons dynamic (5, 7 or 9), based on the current page number. This at least gets rid of some of the padding.
