### ISSUE TITLE
[750$] Migrate e2e suite to Cypress

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#701]
**About This Project**

Nightwatch is the current E2E test framework we use. It is quite old and even though it is maintained it shows its age because it is far behind other E2E frameworks, also it's based on selenium which is known to be slow and has a lot of issues if you start googling it.

One of those frameworks it's lagging behind with is https://www.cypress.io/ which provides an interactive UI that shows the actual website and flow it runs so a developer can see what exactly is happening, going wrong and take action without having to fiddle around on the live application or start to take screenshots in selenium or Nightwatch.
_See the new paper wallet at https://github.com/ArkEcosystem/paper-wallet for a project that uses TypeScript and Cypress._

> The difficulty level of this bounty is estimated as **intermediate**. The reward for completion of this project is set at **$750** (paid in ARK Ѧ).

_Requirements for completion:_
The requirements for this bounty are fairly simple. Migrate all tests from Nightwatch to Cypress without losing any coverage.
_This is the same test setup that the new paper wallet uses, and new projects based on Vue will use too as they come up._

_Necessary Skills:_
- [Cypress](https://www.cypress.io)
- [Nightwatch.js](https://nightwatchjs.org)
- [Vue.JS](https://vuejs.org)

**Applying For This Project**

To apply for this project, please read more about the process below before leaving a comment with the following:

1. A brief proposal relating to the project (e.g. Your experience, how you wish to approach the project, estimated time to completion etc.)
2. Your name and a contact email address (or another form of contact, eg. Slack username) 

**The Process**

Applicant’s will only be permitted to participate in one Tier 0 project at any one time. You can apply for as many projects as you like, but will not be eligible to be accepted until your open projects have been completed. In the meantime the projects may be awarded to other available applicants.

If your application for the project is successful we'll contact you using the details you provided, assign the project to you and mark it as in progress. You'll be required to check in regularly with the ARK team to discuss progress and development. We'll also use these updates to ensure that the PR is being completed to a satisfactory standard. If we determine that the project isn't being completed to a satisfactory standard and that this cannot be achieved with minor amends or within a satisfactory timeframe, we hold the right to dismiss the PR and reopen the project to other applicants.

To deliver the project your PR must be submitted to the respective repo. ARK repo maintainers will then leave comments and request amends if necessary. All amends requested by maintainers must be resolved before completion, and all projects must comply with our code standards and contribution guidelines (found at: https://docs.ark.io/guidebook/contribution-guidelines/). After you've submitted your project, we'll review against the brief to ensure it meets the criteria and deliverables.

Once your project is approved as complete a member of the ARK team will follow up to discuss payment. You'll need to submit an invoice and payment will be issued in (Ѧ) ARK (equivalent to the USD reward value assigned to the project), sent to an address of your choosing. We may need to request additional information regarding your identity in order to comply with our own internal Know Your Customer (KYC) guidelines.

_If you're unsuccessful in applying for this particular project, please consider applying for others. Thanks for your interest and good luck with your application!_

**Comment by dated** [comment]
I would like to submit my application for this bounty as I have extensive experience both with the Explorer application itself as with the current test suite, having written many of the more complicated e2e tests myself.

The completion of this project should not take more than 7 days.

Edgar Goetzendorff / @dated [slack]

**Comment by ItsANameToo** [comment]
Welcome aboard :toot:
