### ISSUE TITLE
Improvement: format block heights

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#757]
Currently the blockheight is only formatted in the heading part of the page that also shows the market cap. We should format the blockheight in other places too, e.g. here https://explorer.ark.io/block/8313be6f8cd555f2ef4580521ca6311392bbccf3bf39c179a4151913ecc2d7ed , to make it easier to read.

**Comment by dated** [comment]
The same can be said about confirmations i guess :lala:
