### ISSUE TITLE
Refactor: use schema for business / bridgechain tx content

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#764]
Both the bridgechain and business transaction assets contain additional information that we should (try to) format in a proper but general way. For example: make links actuals links and display arrays as lists. For this we can use the schemas that the trandaction types adhere to to creste a general formatter for these kind of transactions

**Comment by ItsANameToo** [comment]
for the time being this won't be necessary as the bridgechain properties are already accounted for. When looking into the universal explorer this could be more relevant

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
