### ISSUE TITLE
feat: business / bridgechain details

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#787]
We currently have two pages that list the available businesses and bridgechains. However, this overview is limited in certain ways (e.g. only lists one seedserver while there could be more, no genesis hash, ...). It would be better to make the name clickable, which navigates to a detail screen (similar to transaction details) that lists all the properties of the business / bridgechain.

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
