### ISSUE TITLE
feat: hide recipients on non-transfers

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#884]
Currently every transaction shows a `sender` and `recipient` on its details page. For transfers this makes sense as they are a transaction from one to another (although it could be to the same wallet). All other transactions (with the exception of a timelock transfer) always have the same sender and recipient as they are "special" transactions.

The idea would be to hide the `recipient` on the details page for all transaction types where it's redundant to show it. Examples are 2nd signature generation, votes, delegate registration, multipayment, etc. Especially for multipayment it can remove confusion about it having a "recipient" while it also contains payments that are actually sent to recipients.

Multipayment example with sender / recipient:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/35610748/75546503-f1ca9a80-5a28-11ea-9b03-ecf5fa73d831.png">

**Comment by dated** [comment]
Sounds reasonable. Having the recipient for the "special" transaction types only adds confusion and doesn't hold any valuable information since these transactions only consists of fees spent, there is no actual transfer of value, therefore no real recipient in the broader sense.

**Comment by MatthewDC** [comment]
I agree. It will lower the possibility of confusion for new users and is unnecessary. Removing it makes sense.

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
