### ISSUE TITLE
bug: censored ticket numbers in smartbridge field

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#890]
See https://explorer.ark.io/api/transactions/d8d5710794c93bb3d3b3525b636e3cc93e68b4a939ceacdafcd116358561cc12 (api) https://explorer.ark.io/transaction/d8d5710794c93bb3d3b3525b636e3cc93e68b4a939ceacdafcd116358561cc12 (explorer)

The smartbridge field contains 3 sets of numbers and gets censored, while it shouldn't. Likely due to censorify-it identifying it as a phone number.

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
