### ISSUE TITLE
feat: add status column to delegate table

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#897]
when you click on the "show more" button on the delegate monitor, you end up in a table view of all the delegates. This view should make use of an additional column to make it clearer which delegates are active, on standby and resigned. Right now if you open the table it shows you delegates on rank 51-75 to be in line with the rest of the tables, which can be confusing as 51 is still forging while 52 is not. A column indicating the status should make this more clear.

The reasons we will not go with showing a different amount of rows on these pages are:

- making the table start at 52 brings odd pagination when you would go back to previous pages if you try to keep it at 25 entries per page
- making the table show 51 entries per page so it will be active delegates on page 1, standby delegates on page 2 and onward will bring inconsistencies between the explorer tables (everything else is 25 for example)
- bridgechains can have a different amount of active delegates, so if they only have 5 or 500 it would look odd if the tables are adjusted to the amount of active delegates

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
