### ISSUE TITLE
refactor: change bridgechain creator to address

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#899]
The API only used to return the public key for a bridgechain, but this has been updated now and therefore the explorer should the address for the "creator" column instead

**Comment by dated** [comment]
Changed in #876.

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
