### ISSUE TITLE
feat: custom translations

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/explorer#901]
Once we have the settings page implemented (#900), it should be made possible for a user to input a custom translation to be used by the explorer. The idea will be that there is an input field that accepts a JSON object that contains the translations. Once added, the user will be able to set this translation to be used in the explorer. This will also mean that by default the explorer will only support English officially.

**Comment by brenopolanski** [comment]
@dated maybe you can adapt your CLI (https://github.com/dated/language-plugin-generator) to work with that too

**Comment by faustbrian** [comment]
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.
