### ISSUE TITLE
Confirmation icons missing when using pagination in Desktop viewport

### ISSUE THREAD

**Issue by arkmoon** [ArkEcosystem/explorer#975]
**Expected Behavior**

Transactions that are well confirmed should display the appropriate SVG icons in Desktop view.

**Current Behavior**

Using Pagination on any ARK address in the explorer triggers a network request that gets the next page's HTML. Unfortunately, for whatever reason, the rendered HTML is missing <path> elements for _only the first two rows_ in the results. So, for every page, the first two transactions in the table are apparently missing the double checkmark icon, even when they are well confirmed.

Expected:

```
<g id="Confirmations" transform="translate(-246.365 -4043.25)">
  <g id="check-double-1" transform="translate(495.895 4339.25)">
    <path id="Shape_1757" class="confirmations-st0"
      d="M-230.5-292.5l-9.2 12.3c-.4.6-1.1.7-1.7.3l-.1-.1-2.4-2.4"></path>
    <path id="Shape_1758" class="confirmations-st0" d="M-244.4-279.9c-.5.5-1.2.5-1.7 0l-2.4-2.4"></path>
    <path id="Shape_1759" class="confirmations-st0" d="M-235.2-292.4l-6.6 8.7"></path>
  </g>
</g>
```

Actual:

```
<g id="Confirmations" transform="translate(-246.365 -4043.25)">
  <g id="check-double-1" transform="translate(495.895 4339.25)"></g>
</g>
```
^^^ This only happens for the first two rows, thereafter, the rest of the table is completely fine. Very weird.

<img width="360" alt="Screen Shot 2021-10-07 at 9 48 45 PM" src="https://user-images.githubusercontent.com/29726944/136493074-702de724-1352-4420-99fc-013372b18c13.png">

**Possible Solution**

I haven't determined why this is happening on the backend, but I have narrowed it down to the network request that occurs when you use pagination.

Specifically, when you use pagination, a network request returns HTML from:
Request URL: https://explorer.ark.io/livewire/message/wallet-transaction-table

The HTML in this response is missing the <path> elements for the SVG under the result of effects->html which is what's used to render Page 2, 3, 4, etc.

**Steps to Reproduce**

1. Visit any ARK address with more than 1 page of transactions while in a Desktop viewport size
 e.g. https://explorer.ark.io/wallets/AJ14TXWFGpzYuGQXfES3CFmiDxpbzYeNTz
2. Use the pagination to go to page 2
3. Observe the first two rows are missing the double checkmark icons for the first two rows only, but the rest of the table has them.

**Comment by ItsANameToo** [comment]
@arkmoon thanks for the report, will get it looked at. It's likely caused by ids on the SVGs clashing with one another
