### ISSUE TITLE
nightmode not always working

### ISSUE THREAD

**Issue by crnazmija** [ArkEcosystem/explorer#984]
**Expected Behavior**

To  set nightmode only once.

**Current Behavior**

Getting light mode despite setting it as night

**Possible Solution**

Look into localstorage usage of"nightMode" flag. I see it is set as true, but it's not working for some reason
![image](https://user-images.githubusercontent.com/24563472/138649668-6ba1fabb-908f-45cf-8bbb-d6cc6ece6e4f.png)

**Steps to Reproduce (for bugs)**

Not sure, but seems to manifest on OS restart

**Your Environment**

macOS 11.4
chrome 95.0.4638.54

**Comment by crnazmija** [comment]
this is still happening

**Comment by ItsANameToo** [comment]
https://github.com/ArkEcosystem/explorer/pull/1019 changes how the dark mode setting is handled, which should also fix this issue once it has been deployed
